import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: true,
  clean: true,
  treeshake: true,
  sourcemap: true,
  target: 'es2022',
  external: [
    'react',
    'react-dom',
    'next',
    'next/link',
    'next/navigation',
    'three',
    '@react-three/fiber',
    '@react-three/drei',
    '@react-three/postprocessing',
    '@huggingface/transformers',
    'dexie',
    'docx',
    'jszip',
    'lucide-react',
    'mammoth',
    'marked',
    'pdfjs-dist',
    'postprocessing',
    'xlsx',
    'y-webrtc',
    'yjs',
  ],
});
